### ISSUE TITLE
AttributeError: 'Appr' object has no attribute 'vae'

### ISSUE THREAD

**Issue by salma-emara** [lywang3081/AFEC#2]
Hi Authors, 

Thank you so much for your efforts and for sharing your source code. 

While running this command, `python ./main.py --experiment split_cifar100_SC --approach afec_ewc --lamb 40000 --lamb_emp 1`, I got the following error. 
```
Load data...
Files already downloaded and verified
Files already downloaded and verified
Task order = [19, 2, 20, 9, 11, 18, 7, 14, 5, 3, 6, 15, 10, 8, 17, 12, 4, 1, 16, 13]

Input size = [3, 32, 32] 
Task info = [(0, 5), (1, 5), (2, 5), (3, 5), (4, 5), (5, 5), (6, 5), (7, 5), (8, 5), (9, 5), (10, 5), (11, 5), (12, 5), (13, 5), (14, 5), (15, 5), (16, 5), (17, 5), (18, 5), (19, 5)]
Inits...
Traceback (most recent call last):
  File "/content/drive/MyDrive/AFEC/main.py", line 103, in <module>
    appr = approach.Appr(net, sbatch=args.batch_size, lr=args.lr, nepochs=args.nepochs, args=args, log_name=log_name, empty_net = net_emp)
  File "/content/drive/MyDrive/AFEC/approaches/afec_ewc.py", line 36, in __init__
    self.optimizer=self._get_optimizer()
  File "/content/drive/MyDrive/AFEC/approaches/afec_ewc.py", line 51, in _get_optimizer
    optimizer = torch.optim.Adam(itertools.chain(self.model.parameters(), self.vae.parameters()), lr=lr)
AttributeError: 'Appr' object has no attribute 'vae'
```

Thank you in advance for fixing the issue!

**Comment by lywang3081** [comment]
This bug is due to an old version. I've clean it up.

**Comment by JonnesLin** [comment]
Still happened. Could you recheck it?

**Comment by lywang3081** [comment]
> 

This is the remaining of an old version. You could just delete it.

**Comment by lywang3081** [comment]
> Still happened. Could you recheck it?

I've fixed it.
